# Generated by Django 3.2.25 on 2026-03-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20260128_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When the device was assigned to the user', null=True),
        ),
    ]
