# Generated by Django 3.2.25 on 2026-03-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_auto_20260128_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningsession',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('uploading', 'Uploading / Processing'), ('processed', 'Processed Successfully'), ('failed', 'Processing Failed')], default='pending', help_text='Tracks the status of ZIP payload upload and extraction.', max_length=20),
        ),
    ]
