# Generated by Django 3.2.25 on 2026-03-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_alter_question_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_references/'),
        ),
    ]
