# Generated by Django 3.2.25 on 2026-03-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0008_question_reference_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_multiple_selections',
            field=models.BooleanField(default=False),
        ),
    ]
