# Generated by Django 3.2.25 on 2026-02-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patientvitals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvitals',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='temperature (°F)'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='temperature (°F)'),
        ),
    ]
