# Generated by Django 3.2.25 on 2026-03-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20260228_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='setu_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Setu ID'),
        ),
    ]
